name: Publish to Packagist

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Notify Packagist of new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Packagist
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"repository\": {\"url\": \"https://github.com/${{ github.repository }}.git\"}}" \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"
